package com.ruowei.usercenter.dao.mapper;

import com.ruowei.usercenter.dao.model.BenchBatchRechargeInfo;
import com.ruowei.usercenter.dao.model.BenchBatchRechargeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BenchBatchRechargeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int countByExample(BenchBatchRechargeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int deleteByExample(BenchBatchRechargeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int insert(BenchBatchRechargeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int insertSelective(BenchBatchRechargeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    List<BenchBatchRechargeInfo> selectByExample(BenchBatchRechargeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    BenchBatchRechargeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") BenchBatchRechargeInfo record, @Param("example") BenchBatchRechargeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int updateByExample(@Param("record") BenchBatchRechargeInfo record, @Param("example") BenchBatchRechargeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int updateByPrimaryKeySelective(BenchBatchRechargeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bench_batch_recharge_info
     *
     * @mbggenerated Thu Dec 14 18:35:39 CST 2017
     */
    int updateByPrimaryKey(BenchBatchRechargeInfo record);
}