package com.my.blog.website.model.Vo;

import java.util.Date;

public class SecondHandType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_type.id
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_type.name
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_type.pid
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_type.logoPicUrl
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    private String logopicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_type.create_time
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_type.update_time
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_type.id
     *
     * @return the value of second_hand_type.id
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_type.id
     *
     * @param id the value for second_hand_type.id
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_type.name
     *
     * @return the value of second_hand_type.name
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_type.name
     *
     * @param name the value for second_hand_type.name
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_type.pid
     *
     * @return the value of second_hand_type.pid
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_type.pid
     *
     * @param pid the value for second_hand_type.pid
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_type.logoPicUrl
     *
     * @return the value of second_hand_type.logoPicUrl
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public String getLogopicurl() {
        return logopicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_type.logoPicUrl
     *
     * @param logopicurl the value for second_hand_type.logoPicUrl
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public void setLogopicurl(String logopicurl) {
        this.logopicurl = logopicurl == null ? null : logopicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_type.create_time
     *
     * @return the value of second_hand_type.create_time
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_type.create_time
     *
     * @param createTime the value for second_hand_type.create_time
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_type.update_time
     *
     * @return the value of second_hand_type.update_time
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_type.update_time
     *
     * @param updateTime the value for second_hand_type.update_time
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SecondHandType other = (SecondHandType) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getLogopicurl() == null ? other.getLogopicurl() == null : this.getLogopicurl().equals(other.getLogopicurl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getLogopicurl() == null) ? 0 : getLogopicurl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}