package com.my.blog.website.model.Vo;

import java.math.BigDecimal;
import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_number
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wechat_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wechat_id_2
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String wechatId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.qq
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.weibo
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.passwd
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sexy
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Byte sexy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.register_source
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Byte registerSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.belong_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Byte belongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.register_ip
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.device_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Byte deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.score
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_logo_md5
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String headLogoMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age_group_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Byte ageGroupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_status
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Byte userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.province_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_idCard_number
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private String userIdcardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.authen_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Date authenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.grade
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.integral_score
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    private BigDecimal integralScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @return the value of user_info.real_name
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @param realName the value for user_info.real_name
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_number
     *
     * @return the value of user_info.phone_number
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_number
     *
     * @param phoneNumber the value for user_info.phone_number
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wechat_id
     *
     * @return the value of user_info.wechat_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wechat_id
     *
     * @param wechatId the value for user_info.wechat_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wechat_id_2
     *
     * @return the value of user_info.wechat_id_2
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getWechatId2() {
        return wechatId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wechat_id_2
     *
     * @param wechatId2 the value for user_info.wechat_id_2
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setWechatId2(String wechatId2) {
        this.wechatId2 = wechatId2 == null ? null : wechatId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.qq
     *
     * @return the value of user_info.qq
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.qq
     *
     * @param qq the value for user_info.qq
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.weibo
     *
     * @return the value of user_info.weibo
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.weibo
     *
     * @param weibo the value for user_info.weibo
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.passwd
     *
     * @return the value of user_info.passwd
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.passwd
     *
     * @param passwd the value for user_info.passwd
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sexy
     *
     * @return the value of user_info.sexy
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Byte getSexy() {
        return sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sexy
     *
     * @param sexy the value for user_info.sexy
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setSexy(Byte sexy) {
        this.sexy = sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.register_source
     *
     * @return the value of user_info.register_source
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Byte getRegisterSource() {
        return registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.register_source
     *
     * @param registerSource the value for user_info.register_source
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setRegisterSource(Byte registerSource) {
        this.registerSource = registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.belong_type
     *
     * @return the value of user_info.belong_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Byte getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.belong_type
     *
     * @param belongType the value for user_info.belong_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setBelongType(Byte belongType) {
        this.belongType = belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.register_ip
     *
     * @return the value of user_info.register_ip
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.register_ip
     *
     * @param registerIp the value for user_info.register_ip
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.device_type
     *
     * @return the value of user_info.device_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Byte getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.device_type
     *
     * @param deviceType the value for user_info.device_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setDeviceType(Byte deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.score
     *
     * @return the value of user_info.score
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.score
     *
     * @param score the value for user_info.score
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.head_logo_md5
     *
     * @return the value of user_info.head_logo_md5
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getHeadLogoMd5() {
        return headLogoMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.head_logo_md5
     *
     * @param headLogoMd5 the value for user_info.head_logo_md5
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setHeadLogoMd5(String headLogoMd5) {
        this.headLogoMd5 = headLogoMd5 == null ? null : headLogoMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age_group_type
     *
     * @return the value of user_info.age_group_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Byte getAgeGroupType() {
        return ageGroupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age_group_type
     *
     * @param ageGroupType the value for user_info.age_group_type
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setAgeGroupType(Byte ageGroupType) {
        this.ageGroupType = ageGroupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_status
     *
     * @return the value of user_info.user_status
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_status
     *
     * @param userStatus the value for user_info.user_status
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.province_id
     *
     * @return the value of user_info.province_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.province_id
     *
     * @param provinceId the value for user_info.province_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city_id
     *
     * @return the value of user_info.city_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city_id
     *
     * @param cityId the value for user_info.city_id
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_idCard_number
     *
     * @return the value of user_info.user_idCard_number
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public String getUserIdcardNumber() {
        return userIdcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_idCard_number
     *
     * @param userIdcardNumber the value for user_info.user_idCard_number
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setUserIdcardNumber(String userIdcardNumber) {
        this.userIdcardNumber = userIdcardNumber == null ? null : userIdcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.authen_time
     *
     * @return the value of user_info.authen_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Date getAuthenTime() {
        return authenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.authen_time
     *
     * @param authenTime the value for user_info.authen_time
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setAuthenTime(Date authenTime) {
        this.authenTime = authenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.grade
     *
     * @return the value of user_info.grade
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.grade
     *
     * @param grade the value for user_info.grade
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.integral_score
     *
     * @return the value of user_info.integral_score
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public BigDecimal getIntegralScore() {
        return integralScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.integral_score
     *
     * @param integralScore the value for user_info.integral_score
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    public void setIntegralScore(BigDecimal integralScore) {
        this.integralScore = integralScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfo other = (UserInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getWechatId() == null ? other.getWechatId() == null : this.getWechatId().equals(other.getWechatId()))
            && (this.getWechatId2() == null ? other.getWechatId2() == null : this.getWechatId2().equals(other.getWechatId2()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getWeibo() == null ? other.getWeibo() == null : this.getWeibo().equals(other.getWeibo()))
            && (this.getPasswd() == null ? other.getPasswd() == null : this.getPasswd().equals(other.getPasswd()))
            && (this.getSexy() == null ? other.getSexy() == null : this.getSexy().equals(other.getSexy()))
            && (this.getRegisterSource() == null ? other.getRegisterSource() == null : this.getRegisterSource().equals(other.getRegisterSource()))
            && (this.getBelongType() == null ? other.getBelongType() == null : this.getBelongType().equals(other.getBelongType()))
            && (this.getRegisterIp() == null ? other.getRegisterIp() == null : this.getRegisterIp().equals(other.getRegisterIp()))
            && (this.getDeviceType() == null ? other.getDeviceType() == null : this.getDeviceType().equals(other.getDeviceType()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getHeadLogoMd5() == null ? other.getHeadLogoMd5() == null : this.getHeadLogoMd5().equals(other.getHeadLogoMd5()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAgeGroupType() == null ? other.getAgeGroupType() == null : this.getAgeGroupType().equals(other.getAgeGroupType()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getProvinceId() == null ? other.getProvinceId() == null : this.getProvinceId().equals(other.getProvinceId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getUserIdcardNumber() == null ? other.getUserIdcardNumber() == null : this.getUserIdcardNumber().equals(other.getUserIdcardNumber()))
            && (this.getAuthenTime() == null ? other.getAuthenTime() == null : this.getAuthenTime().equals(other.getAuthenTime()))
            && (this.getGrade() == null ? other.getGrade() == null : this.getGrade().equals(other.getGrade()))
            && (this.getIntegralScore() == null ? other.getIntegralScore() == null : this.getIntegralScore().equals(other.getIntegralScore()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
=======
     * @mbggenerated Fri Dec 15 14:42:45 CST 2017
>>>>>>> parent of 68a0905... update
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getWechatId() == null) ? 0 : getWechatId().hashCode());
        result = prime * result + ((getWechatId2() == null) ? 0 : getWechatId2().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getWeibo() == null) ? 0 : getWeibo().hashCode());
        result = prime * result + ((getPasswd() == null) ? 0 : getPasswd().hashCode());
        result = prime * result + ((getSexy() == null) ? 0 : getSexy().hashCode());
        result = prime * result + ((getRegisterSource() == null) ? 0 : getRegisterSource().hashCode());
        result = prime * result + ((getBelongType() == null) ? 0 : getBelongType().hashCode());
        result = prime * result + ((getRegisterIp() == null) ? 0 : getRegisterIp().hashCode());
        result = prime * result + ((getDeviceType() == null) ? 0 : getDeviceType().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getHeadLogoMd5() == null) ? 0 : getHeadLogoMd5().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAgeGroupType() == null) ? 0 : getAgeGroupType().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getProvinceId() == null) ? 0 : getProvinceId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getUserIdcardNumber() == null) ? 0 : getUserIdcardNumber().hashCode());
        result = prime * result + ((getAuthenTime() == null) ? 0 : getAuthenTime().hashCode());
        result = prime * result + ((getGrade() == null) ? 0 : getGrade().hashCode());
        result = prime * result + ((getIntegralScore() == null) ? 0 : getIntegralScore().hashCode());
        return result;
    }
}