package com.my.blog.website.dao;

import com.my.blog.website.model.Vo.CommentsInfo;
import com.my.blog.website.model.Vo.CommentsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int countByExample(CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int deleteByExample(CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int insert(CommentsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int insertSelective(CommentsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    List<CommentsInfo> selectByExampleWithBLOBs(CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    List<CommentsInfo> selectByExample(CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    CommentsInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByExampleSelective(@Param("record") CommentsInfo record, @Param("example") CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CommentsInfo record, @Param("example") CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByExample(@Param("record") CommentsInfo record, @Param("example") CommentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByPrimaryKeySelective(CommentsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CommentsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByPrimaryKey(CommentsInfo record);
}