package com.my.blog.website.dao;

import com.my.blog.website.model.Vo.RideSharingInfo;
import com.my.blog.website.model.Vo.RideSharingInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RideSharingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int countByExample(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int deleteByExample(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int insert(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int insertSelective(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    List<RideSharingInfo> selectByExample(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    RideSharingInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") RideSharingInfo record, @Param("example") RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int updateByExample(@Param("record") RideSharingInfo record, @Param("example") RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int updateByPrimaryKeySelective(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Fri Dec 22 22:25:31 CST 2017
     */
    int updateByPrimaryKey(RideSharingInfo record);
}