package com.my.blog.website.dao;

import com.my.blog.website.model.Vo.RideSharingInfo;
import com.my.blog.website.model.Vo.RideSharingInfoExample;
<<<<<<< HEAD
import org.apache.ibatis.annotations.Param;

import java.util.List;
=======
import java.util.List;
import org.apache.ibatis.annotations.Param;
>>>>>>> zhichuang/master

public interface RideSharingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int countByExample(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int deleteByExample(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int insert(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int insertSelective(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    List<RideSharingInfo> selectByExampleWithBLOBs(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    List<RideSharingInfo> selectByExample(RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    RideSharingInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByExampleSelective(@Param("record") RideSharingInfo record, @Param("example") RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") RideSharingInfo record, @Param("example") RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByExample(@Param("record") RideSharingInfo record, @Param("example") RideSharingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByPrimaryKeySelective(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(RideSharingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_sharing_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByPrimaryKey(RideSharingInfo record);
}