package com.my.blog.website.dao;

import com.my.blog.website.model.Vo.SecondHandType;
import com.my.blog.website.model.Vo.SecondHandTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondHandTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int countByExample(SecondHandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int deleteByExample(SecondHandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int insert(SecondHandType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int insertSelective(SecondHandType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    List<SecondHandType> selectByExample(SecondHandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    SecondHandType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") SecondHandType record, @Param("example") SecondHandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByExample(@Param("record") SecondHandType record, @Param("example") SecondHandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByPrimaryKeySelective(SecondHandType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_type
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByPrimaryKey(SecondHandType record);
}