package com.my.blog.website.dao;

import com.my.blog.website.model.Vo.SecondHandInfo;
import com.my.blog.website.model.Vo.SecondHandInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondHandInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int countByExample(SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int deleteByExample(SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int insert(SecondHandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int insertSelective(SecondHandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    List<SecondHandInfo> selectByExampleWithBLOBs(SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    List<SecondHandInfo> selectByExample(SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    SecondHandInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByExampleSelective(@Param("record") SecondHandInfo record, @Param("example") SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SecondHandInfo record, @Param("example") SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByExample(@Param("record") SecondHandInfo record, @Param("example") SecondHandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByPrimaryKeySelective(SecondHandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
<<<<<<< HEAD
     * @mbggenerated Tue Dec 19 17:47:27 CST 2017
=======
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SecondHandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_info
     *
     * @mbggenerated Tue Dec 19 09:52:04 CST 2017
>>>>>>> zhichuang/master
     */
    int updateByPrimaryKey(SecondHandInfo record);
}